[files]
extend-exclude = ["**/examples/assets/**", "**/*.urdf", "**/*.usd", "**/*.usda", "**/*.mjcf", "**/*.js"]

[default.extend-words]
lod = "lod"
ba = "ba"
HAA = "HAA"
[default.extend-identifiers]
PNGs = "PNGs"
Haa = "Haa"

